### ISSUE TITLE
Npm module request in week1/promises.js 

### ISSUE THREAD

**Issue by vhrechukha** [VitaliyDanchul/internship2021#1]
Npm module [request](https://www.npmjs.com/package/request) has been **deprecated**. I suggest you to use [axios](https://www.npmjs.com/package/axios) or [got](https://www.npmjs.com/package/got)

      
```
axios.get('https://jsonplaceholder.typicode.com/users')
    .then(({ data }) => {
        resolve(data);
    })
    .catch((error) => {
        reject(error);
    });
```
 
![Screenshot_select-area_20210616145822](https://user-images.githubusercontent.com/50745199/122215790-52971400-ceb4-11eb-9a78-fe0cfd599bc6.png)

**Comment by VitaliyDanchul** [comment]
@crzdvl , in future tasks and projects we will use actual modules. For this task - it's not important.
